In [1]:
import numpy as np
row=int(input("Enter rows in matrix: "))
lst=list()
for _ in range(row):
    l= list(map(int,input("Enter your row: ").split()))
    lst.append(l)
print(lst)

lst= np.array(lst)
print(lst)
trans = lst.T
print(trans)

Enter rows in matrix: 2
Enter your row: 2 3
Enter your row: 1 2
[[2, 3], [1, 2]]
[[2 3]
 [1 2]]
[[2 1]
 [3 2]]


In [2]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))
demo_matrix[2,3]

39

In [4]:
import pandas as pd
score = [10, 15, 20, 25]

pd.Series(data=score, index = ['a','b','c','d'])



a    10
b    15
c    20
d    25
dtype: int64

In [5]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38], [73,39,93,39]))

demo_matrix[:, (1,2)]

array([[35, 74],
       [37, 37],
       [39, 93]])

In [7]:
s1 = pd.Series(['a', 'b'])
s2 = pd.Series(['c', 'd'])
pd.concat([s1, s2])

0    a
1    b
0    c
1    d
dtype: object

In [8]:
data = {'prodID': ['101', '102', '103', '104', '104'],

                    'prodname': ['X', 'Y', 'Z', 'X', 'W'],

                     'profit': ['2738', '2727', '3497', '7347', '3743']}

dataframe = pd.DataFrame(data)

dataframe

grouped_data = dataframe.groupby('prodID')

grouped_data.max()

prodname profit
prodID                
101           X   2738
102           Y   2727
103           Z   3497
104           X   7347

In [9]:
test_array = [10, 11.5, 12, 13.5, 14,15]   

test_array[2:3]

[12]

In [15]:
football=[1,2,3]
np.array(football)

array([1, 2, 3])

In [17]:
np.array['football']

TypeError: 'builtin_function_or_method' object is not subscriptable

In [18]:
np.arange(0,22,6)

array([ 0,  6, 12, 18])